spring.profiles.active: dev

server:
  port: 7050
  servlet:
    context-path: /eapi
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048
  error:
    whitelabel:
      enabled: false
  forward-headers-strategy: native
logging:
  level:
    com.shawn: debug
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: com.shawn.eapi.util.ImprovedNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://127.0.0.1:9092/~/.h2/swagger
    username: sa
    password: sa
    data: classpath:sql/data.sql

  mail:
    host: smtp.163.com
    username: easyapi@163.com
    password: li16200
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  freemarker:
    template-loader-path: classpath:/freemarker
    suffix: .ftl

---
spring:
  profiles: dev
  resources:
    static_locations:
      - file:eapi-editor/dist/
#  devtools:
#    restart:
#      additional_paths:
#        - eapi-editor/dist/
#      additional_exclude: "**/*.js,**/*.css,**/*.html"
  h2:
    server:
      enabled: true
      args: -tcp -web
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
host:
  server: http://localhost:7050/eapi
swagger:
  host: localhost:7050
  contact-email: easyapi@163.com

---
spring:
  profiles: prod
  h2:
    server:
      enabled: true
      args: -tcp -web
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/.h2/swagger-ziroom;AUTO_SERVER=TRUE
    url: jdbc:h2:tcp://127.0.0.1:9092/~/.h2/swagger
    username: sa
    password: sa
    data: classpath:sql/data.sql
host:
  server: http://193.112.105.8/static/eapi-editor/latest/index.html
swagger:
  host: 193.112.105.8:7050
  contact-email: easyapi@163.com