server:
  port: 7050
logging:
  level:
    com.meimeitech: debug
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: com.meimeitech.eapi.util.ImprovedNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/swagger;AUTO_SERVER=TRUE
#    url: jdbc:h2:tcp://192.168.1.103:9092/~/.h2/swagger
#    url: jdbc:h2:tcp://192.168.31.184:9092/~/.h2/swagger
    username: sa
    password: sa
    data: classpath:sql/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  mail:
    host: smtp.163.com
    username: easyapi@163.com
    password: li16200
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  freemarker:
    template-loader-path: classpath:/freemarker
    suffix: .ftl
host:
  server: http://10.133.255.201:5001/pc/swagger-editor/index.html
mail:
  register: "#/user/active"
  forget: "#/user/reset"