spring.profiles.active: dev

server:
  port: 7050
logging:
  level:
    com.meimeitech: debug
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: com.meimeitech.eapi.util.ImprovedNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://127.0.0.1:9092/~/.h2/swagger-ziroom
    username: sa
    password: sa
    data: classpath:sql/data.sql

  mail:
    host: smtp.163.com
    username: easyapi@163.com
    password: li16200
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  freemarker:
    template-loader-path: classpath:/freemarker
    suffix: .ftl

---
spring:
  profiles: dev
  h2:
    server:
      enabled: true
      args: -tcp -web
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
host:
  server: http://localhost:8080
swagger:
  host: localhost:7050
  contact-email: easyapi@163.com

---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/swagger;AUTO_SERVER=TRUE
    username: sa
    password: sa
    data: classpath:sql/data.sql
host:
  server: http://10.133.255.201:5001/pc/swagger-editor/index.html
swagger:
  host: 10.133.255.201:7050
  contact-email: easyapi@163.com